# Generated by Django 4.1 on 2023-02-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adreses', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
                ('from_location', models.CharField(max_length=2)),
                ('to_location', models.CharField(max_length=2)),
                ('inventory_adres', models.CharField(max_length=2)),
                ('inventory_qty', models.CharField(max_length=2)),
                ('from_location_arc', models.CharField(max_length=2)),
                ('to_location_arc', models.CharField(max_length=2)),
            ],
        ),
    ]
